version: '3.8'

services:
  backend-api:
    image: your-backend-image:latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_DATABASE=tool-inventory
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tool-inventory
      MYSQL_USER: santiago
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql